/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mvp_jingshuai_jinapp_NdkTest */

#ifndef _Included_com_mvp_jingshuai_jinapp_NdkTest
#define _Included_com_mvp_jingshuai_jinapp_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mvp_jingshuai_jinapp_NdkTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mvp_jingshuai_jinapp_NdkTest_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_mvp_jingshuai_jinapp_NdkTest
 * Method:    doAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mvp_jingshuai_jinapp_NdkTest_doAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
