/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mvp_jingshuai_jinapp_JniClient */

#ifndef _Included_com_mvp_jingshuai_jinapp_JniClient
#define _Included_com_mvp_jingshuai_jinapp_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mvp_jingshuai_jinapp_JniClient
 * Method:    sayName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mvp_jingshuai_jinapp_JniClient_sayName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
